### ISSUE TITLE
Skapa en klass "Product" i "MarketPlaceEL" mappen

### ISSUE THREAD

**Issue by GlamnikiA** [GlamnikiA/marketplace-da379a#2]
Skapa getters och setters enligt:
The user will specify this information 
about the product: 
o   Its type (e.g., MacBook Pro) 
o   Price 
o   Year of make 
o   Colour 
o   Condition (new, very good, good, not working properly) 

t.ex:
public string type {get; set; } 
public int Price { get; set; }

osv...

**Comment by dank-komrade** [comment]
[Produkt.zip](https://github.com/GlamnikiA/marketplace-da379a/files/8671111/Produkt.zip)
