### ISSUE TITLE
Skapa ett login-form i mappen marketplace

### ISSUE THREAD

**Issue by GlamnikiA** [GlamnikiA/marketplace-da379a#4]
Windows-forms objektet ska ha:

Textruta för användarnamn
Textruta för lösenord
Knapp för att logga in
Knapp för att registrera sig

**Comment by dank-komrade** [comment]
[Form1.DesignerLogin.zip](https://github.com/GlamnikiA/marketplace-da379a/files/8671126/Form1.DesignerLogin.zip)
