### ISSUE TITLE
Skapa windows forms objekt för att registrera sig i mappen "MarketPlace"

### ISSUE THREAD

**Issue by GlamnikiA** [GlamnikiA/marketplace-da379a#5]
Ska finnas textrutor för:
first name, last name, 
date of birth, email address, usernames, and passwords. 

En knapp "Register" 
En knapp "Cancel"

**Comment by dank-komrade** [comment]
[Form1.Designer.zip](https://github.com/GlamnikiA/marketplace-da379a/files/8671120/Form1.Designer.zip)
